# ================================
# LOCAL DEVELOPMENT — H2 In-Memory
# ================================
spring.datasource.url=jdbc:h2:mem:tensorldease;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=VALUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ================================
# JPA CONFIG
# ================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ================================
# APP CONFIG
# ================================
server.port=8080
spring.application.name=tensorldease-backend

# ================================
# JWT CONFIG
# ================================
app.jwt.secret=tensorldease_secret_key_minimum_32_karakter_panjangnya_ini
app.jwt.expiration=86400000

# ================================
# EMAIL CONFIG (disabled locally)
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=farhanhamzah125@gmail.com
spring.mail.password=ozmtibzymdkcdydk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Midtrans config
midtrans.server-key=Mid-server-sQAabR0P2JdjhkV9cW94F6ty
midtrans.client-key=Mid-client-zSHCK3L1qCzGcCor
midtrans.is-production=false
