spring.datasource.url=jdbc:postgresql://localhost:5432/tensorlease_db
spring.datasource.username=postgres
spring.datasource.password=PASSWORD_KAMU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# APP
server.port=8080
spring.application.name=tensorldease-backend

# JWT
app.jwt.secret=tensorldease_secret_key_ganti_dengan_random_string_panjang
app.jwt.expiration=86400000